#!/usr/bin/env python3
"""Generate the app's route pages from one template.

Vitrina serves the same app at three addresses: /shelf/, your own shelf, kept in
this browser or in your account and editable; /demo/, a real collection shown
read-only; and /u/, a shelf somebody chose to share, read-only and named in the
query (/u/?ana). GitHub Pages has no server and no rewrites, so an address needs
a real index.html in a real directory. A route served through 404.html would
answer HTTP 404 to every crawler and link preview, which is the one thing a page
meant for sharing cannot afford, and it is why the name of a shared shelf rides
in the query instead of the path.

Hand-kept copies of a two-hundred-line page drift, which this fleet has watched
happen to its vendored kits more than once, so every page is generated from
_templates/app.html and --check fails `make validate` when any of them is stale.
The template is .html in an underscore directory on purpose: Jekyll leaves
_templates/ out of the published site, and the fleet's fixers (roll-hub-icon.py,
no-em-dash.py, the favicon kit) walk .html files only, so a fleet-wide edit
reaches the template and every page in the same pass.

Only what genuinely differs per route is a placeholder: the head (title,
description, canonical, robots, the Convex deployment the page talks to, and on
/u/ the two metas that keep a shared shelf's address out of analytics and out of
referrers), the header subtitle, the hide-owned label, the footer line, the
banner, and data-mode on <body>. That attribute is what the app reads to decide
whether anything may be edited, and because it is written into the markup
rather than set by a script, the edit controls are hidden before any script runs
instead of flashing on a read-only page and then disappearing. A page that comes
out without it is refused, not written. So is a route whose mode js/state.js
does not list in MODES: the app treats a mode it does not know as the editable
shelf, so a mistyped mode would publish a read-only page that edits and saves.

    python3 scripts/routes.py          write shelf/, demo/ and u/index.html
    python3 scripts/routes.py --check  exit 1 if any of them is stale
"""

import html
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TEMPLATE = os.path.join(ROOT, "_templates", "app.html")
STATE = os.path.join(ROOT, "js", "state.js")
SITE = "https://vitrina.neorgon.com"

TEMPLATE_NOTE = "<!-- Template for /shelf/, /demo/ and /u/. Edit here, then run python3 scripts/routes.py. -->\n"
NOTICE = "<!-- Generated by scripts/routes.py from _templates/app.html. Edit the template, not this file. -->\n"

# The production deployment, the only one a published page may name. The dev
# deployment in .env.local is what `make push-dev` pushes to, and never reaches
# a page.
CONVEX_URL = "https://fantastic-chickadee-557.convex.cloud"
CONVEX_META = '  <meta name="neo-convex-url" content="%s">' % CONVEX_URL

# /u/ only. A shared shelf's address carries its owner's handle, so the page
# counts no visit (the analytics beacon sends the query string and the referrer
# with every hit) and tells other sites its origin and nothing more. It sits
# first in the head, because a referrer policy covers only what comes after it.
PROFILE_HEAD = (
    '  <meta name="neo-analytics" content="off">\n'
    '  <meta name="referrer" content="strict-origin">'
)

# Markup, inserted as written. Everything else is escaped for the attribute or
# text position it lands in.
RAW = {"BANNER", "FOOTER_NOTE", "CONVEX_META", "PROFILE_HEAD"}

# Anything shaped like a placeholder, mistyped ones included. The first version
# only looked for a leftover "{{", so {TITLE}} went out to the page as text.
PLACEHOLDER = re.compile(r"\{+[A-Z][A-Z_]*\}+")

# `export const MODES = ['shelf', ...]`, frozen or not.
MODES_EXPORT = re.compile(r"^export const MODES\s*=\s*(?:Object\.freeze\(\s*)?\[([^\]]*)\]", re.M)

ROUTES = {
    "shelf": {
        "MODE": "shelf",
        "TITLE": "Vitrina | Your own shelf",
        "DESCRIPTION": "Build your own shelf of Spanish science fiction paperbacks from real spine scans, kept in your browser with nothing uploaded",
        "OG_TITLE": "Vitrina: your own shelf",
        "OG_DESCRIPTION": "Your Spanish science fiction paperbacks, standing on a shelf built from their real spine scans",
        "URL": SITE + "/shelf/",
        # A personal shelf lives in one browser or one account and is empty for
        # everyone else, so there is nothing here to index. The home page and
        # the demo carry the search presence.
        "ROBOTS": "noindex, follow",
        "SUBTITLE": "A shelf read by its spines",
        "HIDE_OWNED": "Hide what I own",
        "FOOTER_NOTE": "Your shelf is stored in this browser. Nothing is uploaded.",
        "BANNER": "",
        "CONVEX_META": CONVEX_META,
        "PROFILE_HEAD": "",
    },
    "demo": {
        "MODE": "demo",
        "TITLE": "Vitrina | A real shelf, read-only",
        "DESCRIPTION": "Browse a real collection of Spanish science fiction paperbacks on a shelf built from their real spine scans, each drawn at the height its catalogue record gives",
        "OG_TITLE": "Vitrina: a real shelf of Spanish science fiction",
        "OG_DESCRIPTION": "A real collection of Spanish science fiction paperbacks, read by their spines",
        "URL": SITE + "/demo/",
        "ROBOTS": "index, follow",
        "SUBTITLE": "A real shelf, read-only",
        # The visitor owns none of these, so the label cannot say "I own".
        "HIDE_OWNED": "Hide what is on this shelf",
        "FOOTER_NOTE": 'A real collection, shown read-only. Build your own on <a href="/shelf/">your shelf</a>.',
        "BANNER": (
            '    <div class="demo-banner" role="note">\n'
            '      <p class="demo-banner__text"><strong>A real shelf, read-only.</strong> '
            'This is the collection of the person who built Vitrina, each book drawn at the height its catalogue record gives.</p>\n'
            '      <a class="btn btn--primary btn--sm" href="/shelf/">Start your own shelf</a>\n'
            '    </div>\n'
        ),
        # The demo is library.json and nothing else. With no deployment named,
        # no account shelf can ever be read on this page.
        "CONVEX_META": "",
        "PROFILE_HEAD": "",
    },
    "u": {
        "MODE": "profile",
        "TITLE": "Vitrina | A shared shelf",
        # Generic on purpose. One file serves every shared shelf, and a link
        # preview is built from these before any script runs, so they cannot
        # name whose shelf it is, and must not try.
        "DESCRIPTION": "A shelf of Spanish science fiction paperbacks, shared read-only and drawn from their real spine scans",
        "OG_TITLE": "Vitrina: a shared shelf",
        "OG_DESCRIPTION": "Spanish science fiction paperbacks on a shared shelf, read by their spines",
        "URL": SITE + "/u/",
        # Publishing a shelf is sharing a link, not asking to be in a search index.
        "ROBOTS": "noindex, follow",
        "SUBTITLE": "A shared shelf",
        "HIDE_OWNED": "Hide what is on this shelf",
        "FOOTER_NOTE": 'Shared shelves are read-only. Build your own on <a href="/shelf/">your shelf</a>.',
        # Empty here and filled by the page. It is a live region, so it has to
        # exist before anything is written into it.
        "BANNER": '    <div class="profile-banner" data-profile-banner aria-live="polite"></div>\n',
        "CONVEX_META": CONVEX_META,
        "PROFILE_HEAD": PROFILE_HEAD,
    },
}


def modes(path=STATE):
    """The page modes js/state.js knows, read from its own MODES export."""
    try:
        with open(path, encoding="utf-8") as fh:
            source = fh.read()
    except OSError:
        raise SystemExit("cannot read js/state.js, which lists the modes a route may use")
    match = MODES_EXPORT.search(source)
    if not match:
        raise SystemExit("js/state.js has no `export const MODES = [...]`, so no route's mode can be checked")
    found = [single or double for single, double in re.findall(r"'([^']*)'|\"([^\"]*)\"", match.group(1))]
    if not found:
        raise SystemExit("js/state.js exports an empty MODES")
    return found


def check_modes(routes, known):
    # Every route before any page is written, so a bad route cannot leave the
    # other pages regenerated around it.
    for route, values in routes.items():
        if values["MODE"] not in known:
            raise SystemExit(
                "the %s route has MODE %r, which js/state.js does not list in MODES (%s). "
                "The app would treat it as the editable shelf." % (route, values["MODE"], ", ".join(known))
            )


def render(template: str, values: dict) -> str:
    # A placeholder the template no longer carries drops its value without a
    # word, and for MODE that value is the read-only switch itself.
    missing = [key for key in values if "{{%s}}" % key not in template]
    if missing:
        raise SystemExit("_templates/app.html has no %s" % ", ".join("{{%s}}" % k for k in missing))
    out = template
    for key, value in values.items():
        out = out.replace("{{%s}}" % key, value if key in RAW else html.escape(value, quote=True))
    stray = PLACEHOLDER.search(out)
    if stray:
        raise SystemExit("unfilled or mistyped placeholder %s in the %s route" % (stray.group(0), values["MODE"]))
    body = '<body data-mode="%s">' % values["MODE"]
    if out.count(body) != 1:
        raise SystemExit("the %s page must carry exactly one %s" % (values["MODE"], body))
    named = re.findall(r'<meta name="neo-convex-url" content="([^"]*)">', out)
    if named not in ([], [CONVEX_URL]):
        raise SystemExit("the %s page names Convex deployment(s) %s; a page may name only %s, once"
                         % (values["MODE"], ", ".join(named), CONVEX_URL))
    if TEMPLATE_NOTE not in out:
        raise SystemExit("_templates/app.html lost its header comment")
    return out.replace(TEMPLATE_NOTE, NOTICE, 1)


def main() -> None:
    check = "--check" in sys.argv[1:]
    check_modes(ROUTES, modes())
    with open(TEMPLATE, encoding="utf-8") as fh:
        template = fh.read()

    stale = []
    for route, values in ROUTES.items():
        path = os.path.join(ROOT, route, "index.html")
        page = render(template, values)
        if check:
            current = None
            if os.path.exists(path):
                # newline="" compares the bytes on disk. Text mode folds CRLF
                # into LF, so a page rewritten with Windows line endings used to
                # pass as current.
                with open(path, encoding="utf-8", newline="") as fh:
                    current = fh.read()
            if current != page:
                stale.append(route)
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="") as fh:
            fh.write(page)
        print("wrote %s/index.html" % route)

    if check:
        if stale:
            print("stale route page(s): %s. Run python3 scripts/routes.py"
                  % ", ".join("/%s/" % r for r in stale))
            sys.exit(1)
        print("route pages current: %s" % ", ".join("/%s/" % r for r in ROUTES))


if __name__ == "__main__":
    main()
