#!/usr/bin/env python3
"""Generate the app's route pages from one template.

Vitrina serves the same app at two addresses: /shelf/, your own shelf, kept in
this browser and editable; and /demo/, a real collection shown read-only.
GitHub Pages has no server and no rewrites, so an address needs a real
index.html in a real directory. A route served through 404.html would answer
HTTP 404 to every crawler and link preview, which is the one thing a page meant
for sharing cannot afford.

Two hand-kept copies of a two-hundred-line page drift, which this fleet has
watched happen to its vendored kits more than once, so both pages are generated
from templates/app.html.tmpl and --check fails `make validate` when either is
stale.

Only what genuinely differs per route is a placeholder: the head (title,
description, canonical, robots), the header subtitle, the footer line, the demo
banner, and data-mode on <body>. That attribute is what the app reads to decide
whether anything may be edited, and because it is written into the markup
rather than set by a script, the edit controls are hidden before any script
runs instead of flashing on the demo and then disappearing.

    python3 scripts/routes.py          write shelf/index.html and demo/index.html
    python3 scripts/routes.py --check  exit 1 if either is stale
"""

import html
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TEMPLATE = os.path.join(ROOT, "templates", "app.html.tmpl")
SITE = "https://vitrina.neorgon.com"

TEMPLATE_NOTE = "<!-- Template for /shelf/ and /demo/. Edit here, then run python3 scripts/routes.py. -->\n"
NOTICE = "<!-- Generated by scripts/routes.py from templates/app.html.tmpl. Edit the template, not this file. -->\n"

# Markup, inserted as written. Everything else is escaped for the attribute or
# text position it lands in.
RAW = {"BANNER", "FOOTER_NOTE"}

ROUTES = {
    "shelf": {
        "MODE": "shelf",
        "TITLE": "Vitrina | Your own shelf",
        "DESCRIPTION": "Build your own shelf of Spanish science fiction paperbacks from real spine scans, kept in your browser with nothing uploaded",
        "OG_TITLE": "Vitrina: your own shelf",
        "OG_DESCRIPTION": "Your Spanish science fiction paperbacks, standing on a shelf built from their real spine scans",
        "URL": SITE + "/shelf/",
        # A personal shelf lives in one browser and is empty for everyone else,
        # so there is nothing here to index. The home page and the demo carry
        # the search presence.
        "ROBOTS": "noindex, follow",
        "SUBTITLE": "A shelf read by its spines",
        "FOOTER_NOTE": "Your shelf is stored in this browser. Nothing is uploaded.",
        "BANNER": "",
    },
    "demo": {
        "MODE": "demo",
        "TITLE": "Vitrina | A real shelf, read-only",
        "DESCRIPTION": "Browse a real collection of Spanish science fiction paperbacks, each standing at the height of the book on a shelf built from real spine scans",
        "OG_TITLE": "Vitrina: a real shelf of Spanish science fiction",
        "OG_DESCRIPTION": "A real collection of Spanish science fiction paperbacks, read by their spines",
        "URL": SITE + "/demo/",
        "ROBOTS": "index, follow",
        "SUBTITLE": "A real shelf, read-only",
        "FOOTER_NOTE": 'A real collection, shown read-only. Build your own on <a href="/shelf/">your shelf</a>.',
        "BANNER": (
            '    <div class="demo-banner" role="note">\n'
            '      <p class="demo-banner__text"><strong>A real shelf, read-only.</strong> '
            'This is the collection of the person who built Vitrina, every book standing at the height of the real paperback.</p>\n'
            '      <a class="btn btn--primary btn--sm" href="/shelf/">Start your own shelf</a>\n'
            '    </div>\n'
        ),
    },
}


def render(template: str, values: dict) -> str:
    out = template
    for key, value in values.items():
        out = out.replace("{{%s}}" % key, value if key in RAW else html.escape(value, quote=True))
    if "{{" in out:
        raise SystemExit("unfilled placeholder in the %s route" % values["MODE"])
    if TEMPLATE_NOTE not in out:
        raise SystemExit("templates/app.html.tmpl lost its header comment")
    return out.replace(TEMPLATE_NOTE, NOTICE, 1)


def main() -> None:
    check = "--check" in sys.argv[1:]
    with open(TEMPLATE, encoding="utf-8") as fh:
        template = fh.read()

    stale = []
    for route, values in ROUTES.items():
        path = os.path.join(ROOT, route, "index.html")
        page = render(template, values)
        if check:
            current = None
            if os.path.exists(path):
                with open(path, encoding="utf-8") as fh:
                    current = fh.read()
            if current != page:
                stale.append(route)
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(page)
        print("wrote %s/index.html" % route)

    if check:
        if stale:
            print("stale route page(s): %s. Run python3 scripts/routes.py"
                  % ", ".join("/%s/" % r for r in stale))
            sys.exit(1)
        print("route pages current: %s" % ", ".join("/%s/" % r for r in ROUTES))


if __name__ == "__main__":
    main()
