#!/usr/bin/env python3
"""Generate the app's route pages from one template.

Vitrina serves the same app at two addresses: /shelf/, your own shelf, kept in
this browser and editable; and /demo/, a real collection shown read-only.
GitHub Pages has no server and no rewrites, so an address needs a real
index.html in a real directory. A route served through 404.html would answer
HTTP 404 to every crawler and link preview, which is the one thing a page meant
for sharing cannot afford.

Two hand-kept copies of a two-hundred-line page drift, which this fleet has
watched happen to its vendored kits more than once, so both pages are generated
from _templates/app.html and --check fails `make validate` when either is
stale. The template is .html in an underscore directory on purpose: Jekyll
leaves _templates/ out of the published site, and the fleet's fixers
(roll-hub-icon.py, no-em-dash.py, the favicon kit) walk .html files only, so a
fleet-wide edit reaches the template and both pages in the same pass.

Only what genuinely differs per route is a placeholder: the head (title,
description, canonical, robots), the header subtitle, the hide-owned label, the
footer line, the demo banner, and data-mode on <body>. That attribute is what
the app reads to decide whether anything may be edited, and because it is
written into the markup rather than set by a script, the edit controls are
hidden before any script runs instead of flashing on the demo and then
disappearing. A page that comes out without it is refused, not written.

    python3 scripts/routes.py          write shelf/index.html and demo/index.html
    python3 scripts/routes.py --check  exit 1 if either is stale
"""

import html
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TEMPLATE = os.path.join(ROOT, "_templates", "app.html")
SITE = "https://vitrina.neorgon.com"

TEMPLATE_NOTE = "<!-- Template for /shelf/ and /demo/. Edit here, then run python3 scripts/routes.py. -->\n"
NOTICE = "<!-- Generated by scripts/routes.py from _templates/app.html. Edit the template, not this file. -->\n"

# Markup, inserted as written. Everything else is escaped for the attribute or
# text position it lands in.
RAW = {"BANNER", "FOOTER_NOTE"}

# Anything shaped like a placeholder, mistyped ones included. The first version
# only looked for a leftover "{{", so {TITLE}} went out to the page as text.
PLACEHOLDER = re.compile(r"\{+[A-Z][A-Z_]*\}+")

ROUTES = {
    "shelf": {
        "MODE": "shelf",
        "TITLE": "Vitrina | Your own shelf",
        "DESCRIPTION": "Build your own shelf of Spanish science fiction paperbacks from real spine scans, kept in your browser with nothing uploaded",
        "OG_TITLE": "Vitrina: your own shelf",
        "OG_DESCRIPTION": "Your Spanish science fiction paperbacks, standing on a shelf built from their real spine scans",
        "URL": SITE + "/shelf/",
        # A personal shelf lives in one browser and is empty for everyone else,
        # so there is nothing here to index. The home page and the demo carry
        # the search presence.
        "ROBOTS": "noindex, follow",
        "SUBTITLE": "A shelf read by its spines",
        "HIDE_OWNED": "Hide what I own",
        "FOOTER_NOTE": "Your shelf is stored in this browser. Nothing is uploaded.",
        "BANNER": "",
    },
    "demo": {
        "MODE": "demo",
        "TITLE": "Vitrina | A real shelf, read-only",
        "DESCRIPTION": "Browse a real collection of Spanish science fiction paperbacks on a shelf built from their real spine scans, each drawn at the height its catalogue record gives",
        "OG_TITLE": "Vitrina: a real shelf of Spanish science fiction",
        "OG_DESCRIPTION": "A real collection of Spanish science fiction paperbacks, read by their spines",
        "URL": SITE + "/demo/",
        "ROBOTS": "index, follow",
        "SUBTITLE": "A real shelf, read-only",
        # The visitor owns none of these, so the label cannot say "I own".
        "HIDE_OWNED": "Hide what is on this shelf",
        "FOOTER_NOTE": 'A real collection, shown read-only. Build your own on <a href="/shelf/">your shelf</a>.',
        "BANNER": (
            '    <div class="demo-banner" role="note">\n'
            '      <p class="demo-banner__text"><strong>A real shelf, read-only.</strong> '
            'This is the collection of the person who built Vitrina, each book drawn at the height its catalogue record gives.</p>\n'
            '      <a class="btn btn--primary btn--sm" href="/shelf/">Start your own shelf</a>\n'
            '    </div>\n'
        ),
    },
}


def render(template: str, values: dict) -> str:
    # A placeholder the template no longer carries drops its value without a
    # word, and for MODE that value is the read-only switch itself.
    missing = [key for key in values if "{{%s}}" % key not in template]
    if missing:
        raise SystemExit("_templates/app.html has no %s" % ", ".join("{{%s}}" % k for k in missing))
    out = template
    for key, value in values.items():
        out = out.replace("{{%s}}" % key, value if key in RAW else html.escape(value, quote=True))
    stray = PLACEHOLDER.search(out)
    if stray:
        raise SystemExit("unfilled or mistyped placeholder %s in the %s route" % (stray.group(0), values["MODE"]))
    body = '<body data-mode="%s">' % values["MODE"]
    if out.count(body) != 1:
        raise SystemExit("the %s page must carry exactly one %s" % (values["MODE"], body))
    if TEMPLATE_NOTE not in out:
        raise SystemExit("_templates/app.html lost its header comment")
    return out.replace(TEMPLATE_NOTE, NOTICE, 1)


def main() -> None:
    check = "--check" in sys.argv[1:]
    with open(TEMPLATE, encoding="utf-8") as fh:
        template = fh.read()

    stale = []
    for route, values in ROUTES.items():
        path = os.path.join(ROOT, route, "index.html")
        page = render(template, values)
        if check:
            current = None
            if os.path.exists(path):
                # newline="" compares the bytes on disk. Text mode folds CRLF
                # into LF, so a page rewritten with Windows line endings used to
                # pass as current.
                with open(path, encoding="utf-8", newline="") as fh:
                    current = fh.read()
            if current != page:
                stale.append(route)
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="") as fh:
            fh.write(page)
        print("wrote %s/index.html" % route)

    if check:
        if stale:
            print("stale route page(s): %s. Run python3 scripts/routes.py"
                  % ", ".join("/%s/" % r for r in stale))
            sys.exit(1)
        print("route pages current: %s" % ", ".join("/%s/" % r for r in ROUTES))


if __name__ == "__main__":
    main()
